theme: jekyll-theme-cayman
title: [Modelagem matemática da disseminação geográfica da COVID-19]
description: [Predição, estratégias de mitigação e supressão, distribuição de recursos]
google_analytics: UA-11286782-10
